SNEWS2/snewpy

python/snewpy/models.py

> Note that the x neutrino luminosity is for **one** neutrino flavor - to get the total mu/tau neutrino and antineutrino luminosities requires multiplying this number by 4.
(from https://doi.org/10.5281/zenodo.3667908)
Accordingly, the nu_x luminosity should not be divided by 4 when reading in data from these files. This PR removes that factor and, while I’m at it, adds the journal reference and the DOI link for the neutrino fluxes.

remove constant factor from Warren_2020 model

---

.github/workflows/publish.yml

Creating a new release (in addition to a tag) will display it on the GitHub repo main page and push it to Zenodo.
With this PR, the workflow creates a draft release; we still need to manually fill in a brief summary of important changes and publish it.

create draft release after publishing to PyPI

---

python/snewpy/models.py

The [documentation of `__repr__()`](https://docs.python.org/3/reference/datamodel.html?highlight=__repr__#object.__repr__) says:
> If at all possible, this should look like a valid Python expression that could be used to recreate an object with the same value (given an appropriate environment).
Accordingly, this PR introduces a generic `__repr__()` implementation for all `SupernovaModel` subclasses, so that e.g.:
```
>>> n = Nakazato_2013('path/to/nakazato-LS220-BH-z0.004-s30.0.fits')
>>> repr(n)
"Nakazato_2013('nakazato-LS220-BH-z0.004-s30.0.fits')"
```
The existing `__repr__()` implementations for individual models print out a nicely printable string representation like
```
Nakazato_2013 Model: nakazato-LS220-BH-z0.004-s30.0.fits
Progenitor mass : 30.0 solMass
Metallicity     : 0.004 …
```

add generic __repr__ for SupernovaModels

---

python/snewpy/snowglobes.py

The two model names weren’t linked to their respective `SupernovaModel` subclasses in `generate_fluence()` and `generate_time_series()`, causing an error when trying to use them.
Thank to @RemiHill for discovering this!

fix KeyError when trying to use Kuroda_2020 or Fornax_2019 model

---

doc/nb/AnalyticFluence.ipynb
doc/nb/SNEWPY_examples.ipynb
python/snewpy/from_snowglobes.py
python/snewpy/scripts/SNEWS2.0_rate_table.py
python/snewpy/scripts/SNEWS2.0_rate_table_singleexample.py
python/snewpy/snowglobes.py

Remove `return_tables` argument and always return them. The performance cost of reading this data is negligible, and if the user doesn’t need it, they can always ignore the return value.

always return data tables from collate()

---

python/snewpy/flavor_transformation.py

These changes compute the NeutrinoDecay probabilities using numpy broadcasting. It should run considerably faster. Running Flavor_XForm.ipynb locally, the cells associated with NeutrinoDecay ran 86 times faster (evaluated by ipython `timeit` magic command).
Fixes #31, closes #34

Vectorize NeutrinoDecay

---

python/snewpy/snowglobes.py
python/snewpy/test/snowglobes_integrationtest.py

Fixes #122, where SNEWPY would cut off the initial digit of the event count when reading SNOwGLoBES files.
@soso128: In my testing, this has been fixed. Can you please check out this branch and confirm whether it fixes the issue?

fix reading from SNOwGLoBES files

---

.github/workflows/integration.yml

I think my commits might have been heavy for the runner, sorry.
Let's run the tests only when pull request is in a ready state.

Prevent running integration tests on draft PR

---

python/snewpy/snowglobes.py

This PR
* cleans up some unused code and imports that were left over from re-writing the `collate` function
* moves all imports to the top of the module
* replaces the hardcoded name of the cache file (that is created in `simulate` and read in `collate`) with one that is analogous to the tarball file name

SNOwGLoBES interface cleanup

---

python/snewpy/__init__.py

This closes #145 by adding an improved error message if a model file download fails.
Additionally, now that the Jupyter notebooks demonstrating each model are downloaded together with the model files, this PR ensures that the notebooks are re-downloaded even when they already exist locally. That’s because unlike existing model files (which shouldn’t change to avoid confusion) these notebooks may be updated over time as more progenitors for that model are added or as the SNEWPY API evolves.

Model download improvements

---

python/snewpy/snowglobes.py

With the rewrite of the SNOwGLoBES interface in #132, several parameters to `simulate()` and `collate()` are no longer used. To avoid confusing users, this PR updates the docstrings to note that these parameters are deprecated and prints a warning message if one of these parameters is used.

`snewpy.snowglobes`: note deprecated parameters

---

python/snewpy/scripts/Convert_to_ROOT.py
python/snewpy/snowglobes.py
python/snewpy/snowglobes_interface.py

Since someone in my group didn't want to install GLoBES, I modified the Snowglobes interface to allow to compute the expected rates using only the SNOwGLoBES detector configurations and cross-sections. Here, the rates are computed for a perfect detector (no smearing, 100% efficiencies). I added options in snowglobles.simulate and snowglobes.collate in order to choose to compute this rate if needed.
Running this code for IceCUBE and for the Nakazato 2013 model with 30 bins (default options in scripts/TimeSeries.py), I found that the discrepancies between the new and old unsmeared rates were of at most 0.4%.

Add rate computation without GLOBES

---

python/snewpy/models/base.py

Fixes `PinchedModel.__init__()` to check whether 'L_NU_X_BAR' is among the column names; previously, it looked for that string in the table entries.
(This means that before this fix, SNEWPY would always use NU_X data for NU_X_BAR columns, even if NU_X_BAR data had been provided. In practice, none of the included models did provide NU_X_BAR data separately, so this didn’t have any effects.)
This fixes a `FutureWarning` (NumPy <=1.22) or `TypeError` (NumPy 1.23) in the tests and makes them run faster as a side effect. (Comparing the string to a handful of column names, rather than to thousands of table rows, saves _a lot_ of time.)

Fix flavour check for `PinchedModel`

---

.gitignore

Ignore output files from running `snewpy.snowglobes` as well as files generated during integration tests in `test_snowglobes.py`.

extend .gitignore list

---

requirements.txt

Fixes #188. AstroPy 4.3 still supports Python 3.7 or higher (same as SNEWPY), so this won’t affect backwards compatibility.

Require AstroPy >=4.3

---

python/snewpy/snowglobes_interface.py

This should close issue #205
The problem was the following:
- guess_material() was not considering the '_he' in the material name, which was causing that efficiency and smearing files were not found, and those matrices were set to ones. This was producing no error in the ar40kt_he case, but it was not properly running with he eff and smear files.
- for the case of wc100kt30prct_he detector, the oxygen files don't contain '_he' in the channel, but ibd and nu-e ES do. So for the oxygen case, the file name was correctly found, but there was a missmatch with the rates binning, which was set only for the non he case.

Fix issue with he detectors

---

.github/workflows/publish.yml
python/snewpy/__init__.py
python/snewpy/_version.py

As [suggested last week](https://github.com/SNEWS2/snewpy/pull/184#issuecomment-1275059998), this is a new beta release to test more broadly that the changes introduced in #184 are backwards compatible with existing code.
In addition, this PR includes a minor fix to ensure snewpy can be installed in a clean environment without separately installing astropy first. (This caused the readthedocs page for the main branch to fail to build.)

Release v1.3b2

---

.github/workflows/integration.yml
python/snewpy/test/simplerate_integrationtest.py
python/snewpy/test/test_05_snowglobes.py
setup.py

In #128, we changed the GitHub workflow so that integration test would not run on draft PRs. Unfortunately, with the solution we found back then, it required manual activity by a developer to run; so it did not run reliably on PRs, which has caused some problems recently.
After looking at the GitHub documentation some more, I think I’ve found a better way to achieve the same thing. I will test in this PR.

Skip integration test for draft PRs

---

.github/workflows/integration.yml
.github/workflows/publish.yml
.github/workflows/tests.yml
requirements.txt
setup.py

Python 3.11 [was released in late October](https://www.python.org/downloads/release/python-3110/), so this PR adds it to our testing matrix. Looking at the [3.11 release notes](https://docs.python.org/3.11/whatsnew/3.11.html), we should need no further changes for compatibility. Unfortunately, one of snewpy’s dependencies (`h5py`) [hasn’t yet published](https://github.com/h5py/h5py/pull/2165#issuecomment-1302303865) a release that supports 3.11, so unless we install `h5py` from source, snewpy will not yet install under 3.11; so this PR is currently a draft.
At the same time, I would suggest dropping support for Python 3.7 with the next snewpy release. This is in line with much of the scientific Python ecosystem (who [dropped 3.7 support in December …

add Python 3.11 to test suite; drop 3.7

---

.github/workflows/integration.yml
README.md
doc/nb/AnalyticFluence.ipynb
doc/nb/SNOwGLoBES_usage.ipynb
doc/source/snowglobes.rst
python/snewpy/scripts/SNEWS2.0_rate_table.py
python/snewpy/scripts/SNEWS2.0_rate_table_singleexample.py
python/snewpy/scripts/TimeSeries.py
python/snewpy/scripts/snewpy_to_snewpdag.py
python/snewpy/snowglobes.py
python/snewpy/snowglobes_interface.py
python/snewpy/test/simplerate_integrationtest.py
requirements.txt

Closes #208. I’ve just filed SNOwGLoBES/snowglobes#21, which would help publish SNOwGLoBES data files as a PyPI package. This would simplify snewpy installation (users no longer need to download SNOwGLoBES manually) and usage (no need to specify the SNOwGLoBES directory in `snewpy.snowglobes` function calls).
To test this:
1. Run `pip install -i https://test.pypi.org/simple/ snowglobes_data`
2. Then install snewpy from this branch
3. Open `SNOwGLoBES_usage.ipynb` and set `SNOwGLoBES_path` to `None`.
This PR is currently marked as a draft, because there are a few open To-Dos:

Use snowglobes_data package instead of hardcoded path

---

.gitignore
python/snewpy/_version.py

With #236 merged, this is a beta release to let people test the new neutrino flux container classes.

Release version 1.4b2

---

python/snewpy/flux.py
python/snewpy/test/test_flux_container.py

Call "decompose" each time a new Container is created - this should prevent situations like _"cm2/cm2"_ or _"h/min"_ units. 
**Note:** this reduces the units to SI bases. If we want, we can list standard SNEWPY units here, so everything will be converted to them instead.

Fixes #267: explicitly call the units decomposition on Container creation

---

README.md
doc/source/citing.rst
doc/source/contributing.rst

Several improvements to the documentation pages and README:
* Improved instructions for how to contribute to and cite SNEWPY in the docs pages
* README now links to the docs page on how to contribute, rather than duplicating part of that content.
* Updates the README file with short sample code snippets to be more welcoming to new users
Thanks to @santosmv for suggesting the sample code snippets!

Improve docs

---

models/Tamborra_2014/Tamborra_2014.ipynb
models/Walk_2018/Walk_2018.ipynb
models/Walk_2019/Walk_2019.ipynb
python/snewpy/neutrino.py

This fixes #277, #278 and #280.
The first two commits are just updating example notebooks to account for additional models we’ve added in v1.4.
The third one changes the name of an optional parameter to `MixingParameters` from `mass_order` back to `mh` (which it was in v1.3 and earlier). I’d like to release a v1.4.1 ASAP, to avoid anyone else running into issues with this.

Update Jupyter notebooks

---

python/snewpy/_model_downloader.py

Mostly refactoring: same functionality, but using a more object-oriented approach.
1) Mostly refactoring: keeps the same functionality, calling `snewpy._model_downloader.get_model_data`
2) A global variable `registry` is defined and reused, so no need to read `model_files.yml` every time a model requests a file - it is read only once.
3) New feature: implements #269. This is not actually used now, but will be useful later, when we include preSN

Update model downloader

---

python/snewpy/models/ccsn.py
python/snewpy/test/test_01_registry.py

Closes #293.
Change Fornax_2022 input from "progenitor" string to progenitor_mass.Store 'Black hole' flag in metadata.
Also I changed the description values for the progenitor_mass from `["9.0".."26.99"]` to the full list of options. This helps the user to see what was the problem, if they provide non-existing input. 
In my opinion this is more helpful:
```
ValueError: Invalid parameter value for 'progenitor_mass'=12.3 solMass. Allowed values are: [ 9.    9.25  9.5   9.75 10.   10.25 10.5  10.75 11.   11.25 11.5  11.75
12.   12.03 12.07 12.1  12.13 12.15 12.18 12.2  12.25 12.33 12.4  12.45
12.5  12.54 12.6  12.63 12.7  12.72 12.75 12.8  12.85 12.9  12.93 12.97
13.   13.05 13.11 13.25 13.27 13.32 13.4  13.45 13.5  13.6  13.75 13.82
13.9  13.96 14.01 14.13 14.25 14.4  14.41 14.43 14.44 14.7 …
```

 Change Fornax_2022 input to progenitor_mass

---

python/snewpy/flux.py
python/snewpy/test/test_flux_container.py

Fixing problem if a user passes a scalar value to container. 
Example:
```python
import numpy as np
import astropy.units as u
from snewpy.flux import Flux
from snewpy.neutrino import Flavor
Flux(data = [1] << u.Unit('1/(MeV s cm**2)'), 
flavor=[Flavor.NU_E],
time=[1]<<u.s,
energy=[1]<<u.MeV)
#now it's possible to pass scalars if there is only a single value or point
Flux(data = 1 << u.Unit('1/(MeV s cm**2)'), 
flavor=Flavor.NU_E, 
time=1<<u.s,
energy=1<<u.MeV)
#they're converted internally to arrays. This produces 
```

Allow scalar input for 't', 'E' and 'data' arguments of Container class

---

python/snewpy/models/loaders.py

Fixes #259.
Additionally fixes a bug I discovered during this work, where for `interpolation="nearest"` a scalar value for E (e.g. `10*u.MeV`) would crash and a length-1 array (e.g. `[10]*u.MeV`) was required instead.
In addition to the usual tests, I’ve verified manually that the outputs for a few example t/E values were unchanged before/after this change. Additionally, I ran some performance checks, comparing the old and new versions with the following code snippet:
```Python
from snewpy.neutrino import Flavor
from snewpy.models.ccsn import Fornax_2021
from astropy import units as u
import numpy as np
fornax = Fornax_2021(progenitor_mass=Fornax_2021.param['progenitor_mass'][1])
n_times = 100  # set this to 1, 10, 100 for benchmarking
times = np.linspace(1, 2, n_times) * u.s
for t in …
```

times broadcasting for Fornax_2021

---

python/snewpy/models/ccsn_loaders.py

Resolves #316 (the second part), see discussion there.

Mori_2023: don’t duplicate metadata dict entries into instance variables

---

.github/workflows/publish.yml
python/snewpy/__init__.py
python/snewpy/_model_urls.py
python/snewpy/models/__init__.py
python/snewpy/test/test_02_models.py

One more problem discovered while preparing the v1.5 release: The bulk downloader (`snewpy.get_models()`) broke when moving model files to separate repositories.
This PR fixes it and ensures it uses the same download code as model initialisers (iterating over all parameter_combinations, rather than using its own dictionary of hardcoded file names); to avoid future breakage.
As a side effect, the bulk downloader will now download to the same `snewpy.model_path`, rather then the current directory. This is good for consistency and may avoid duplicate downloads.
The parameter `download_dir` was never officially documented; I’m still marking it as deprecated though, to be safe.

Fix bulk downloader

---

.github/workflows/tests.yml
doc/Makefile
python/snewpy/models/presn.py

Fixes #327.
In addition to fixing the warning itself, this includes measures to more quickly discover similar issues in the future:
This PR now treats warnings as errors in our docs Makefile, consistent with ReadTheDocs’ configuration. It also builds docs as part of our CI workflows, so we notice future issues on every PR and can fix them before merging broken docs into `main`.

Fix docs build and add it to CI workflow

---

doc/nb/presn/Yoshida_2016.ipynb
python/snewpy/models/model_files.yml
python/snewpy/models/presn.py
python/snewpy/models/presn_loaders.py
python/snewpy/test/test_presn_rates.py

Add presn.Yoshida_2016 model

---

python/snewpy/flavor.py
python/snewpy/flux.py
python/snewpy/models/base.py
python/snewpy/neutrino.py
python/snewpy/test/test_flavors.py
python/snewpy/test/test_flux_container.py

This is a suggestion for #309 
* `flavors1`, `flavors2`: children of `FlavorScheme`flavor schemes - it means that matrix transforms from `flavor1` space to `flavors2`
* `array: np.ndarray` the matrix itself
See the description below

Adding the implementation of the FlavorScheme and FlavorMatrix

---

.github/workflows/integration.yml
.github/workflows/tests.yml
python/snewpy/_model_downloader.py
python/snewpy/flux.py
python/snewpy/neutrino.py
python/snewpy/rate_calculator.py
requirements.txt
setup.py

This PR drops support for Python 3.8 and cleans up some backwards compatibility code.
Python 3.8 is [scheduled to reach end-of-life this autumn](https://peps.python.org/pep-0569/#lifespan); and many major packages in the scientific Python ecosystem already started dropping 3.8 support [since April 2023](https://numpy.org/neps/nep-0029-deprecation_policy.html).
@Sheshuk: If there are any places in the SNEWPY 2.0 code where support for Python 3.9 is holding us back, we can consider dropping 3.9 support as well. (NumPy and others started doing that in April 2024.)

Drop Python 3.8 and 3.9 Support

---

.github/workflows/integration.yml
.github/workflows/tests.yml
python/snewpy/models/ccsn.py
python/snewpy/test/test_flux_container.py

This should eventually fix #340.

Fix Windows-specific bugs

---

python/snewpy/models/base.py

PR to address #257, suppressing numpy's div-by-zero warnings that are not a problem for the flux calculation.

Suppress div-by-zero warning in spectrum calc.

---

python/snewpy/models/ccsn.py
python/snewpy/models/registry_model.py
python/snewpy/snowglobes.py
python/snewpy/test/test_01_registry.py

This PR is intended to remove deprecations in the SN model initialisers, including initialising from a file name and inconsistent keyword arguments.
There are still a couple of `@deprecated` decorators we should remove before merging this. (E.g. for many models, the `eos` keyword is marked as deprecated, because there is only a single possible value; so it shouldn’t be required as part of the `__init__`.)
I think the best way to proceed there would be to remove `eos` from the parameter list and manually set `self.metadata["eos"]` in the `__init__` to the fixed value instead. I’ll do that tomorrow and mark this as a draft PR until then; but wanted to get it out now before I go to bed, in case you want to review this during your daytime, @Sheshuk. (Yay for timezones! 😉)
(Also: Yes, I’ve …

Remove deprecated arguments from SN model initialisers

---

python/snewpy/__init__.py

This should work better under Windows.

avoid hard-coded directory separator in model_path

---

doc/nb/ccsn/Fischer_2020.ipynb
python/snewpy/models/ccsn.py

Working on #356 I noticed that there were a few more SN model classes that had only a single option for the `eos` argument but where it wasn’t marked as `@deprecated`. This PR adds deprecation markers to those models; in line with the docstring of the `GarchingArchiveModel` class (which these four models all inherit from).
For the `Fischer_2020` model, which was just added in #347, I’m also moving the `eos` argument to a metadata field. (No deprecation necessary here, because this was never in a published release.)

EOS deprecations

---

.github/workflows/integration.yml
.github/workflows/tests.yml
python/snewpy/snowglobes_interface.py
requirements.txt
setup.py

Python 3.13 was released last week and 3.8 [reached end-of-life](https://devguide.python.org/versions/) at the same time. This PR updates our testing matrix accordingly and removes some compatibility workarounds that are no longer necessary.

Support Python 3.13 (and drop 3.8)

---

python/snewpy/neutrino.py

The regular-ish update. This PR leaves NuFIT 5.0 as the default value; though we should probably update that later for the v2.0 release.

Add NuFIT 6.0 and PDG 2024 oscillation parameter presets

---

python/snewpy/models/presn_loaders.py

Our supernova models have `SupernovaModel.time` attribute which contains the intrinsic time values - which in many cases define the valid time range of the given model.
For the presupernova models this time range should be negative (i.e. time before collapse).
But currently `.time` is negative only for Odrzywolek, and positive for all others.
This PR corrects that.

Initializing all preSN models with negative time
