python/snewpy/models.py

Cleanup: the FornaxModel code, which used this import, was removed in #47

remove photospline import

---

.gitignore

Ignore build products and editor settings in commands like `git status`.

add basic .gitignore file

---

README.md
doc/source/gettingstarted.rst
doc/source/index.rst

Updates the README file and adds a page to the sphinx documentation.

document installation process

---

doc/source/neutrino.rst

remove bullet points that were accidentally copied over from a different page

[DOC] Update neutrino.rst

---

doc/source/contributing.rst
doc/source/index.rst

[DOC] improved homepage, add Contributing section

---

doc/source/conf.py
doc/source/contributing.rst
doc/source/gettingstarted.rst
doc/source/models.rst
doc/source/neutrino.rst
doc/source/transformations.rst
python/snewpy/flavor_transformation.py
python/snewpy/models.py
python/snewpy/neutrino.py

Autodoc improvements for `snewpy.models` and `snewpy.flavor_transformation`; mainly hiding duplicate docstrings or internal methods.
Improved/added docstrings for `snewpy.neutrino`.
This solves some parts of #76.

[DOC] autodoc improvements and docstring updates

---

.github/workflows/tests.yml
README.md
doc/paper.md
doc/source/gettingstarted.rst
doc/source/models.rst
doc/source/snowglobes.rst
doc/source/transformations.rst

A few minor updates from collaboration review. Still need to update the author list.

[JOSS Paper] updates from collaboration review

---

python/snewpy/models.py
python/snewpy/test/test_models.py

Make sure all documented models have unit tests demonstrating they can be initialized.

Flesh out model unit tests.

---

python/snewpy/__init__.py

add error message when model_urls is empty

---

README.md
doc/paper.bib
doc/paper.md
doc/source/contributing.rst

This should fix #111.
It also includes some improvements to the JOSS paper in response to @apizzuto’s feedback in openjournals/joss-reviews#3772.

Update README and documentation

---

python/snewpy/snowglobes_interface.py

This PR is intended to fix #155.
As discussed there, it only fixes the first part currently, so I’ll keep it as a draft.

asyncio fixes under Python 3.7

---

.github/workflows/integration.yml
.github/workflows/tests.yml

Prevent publishing benchmark results on main (so it won't crash the test)

Improve test workflows

---

python/snewpy/snowglobes_interface.py
python/snewpy/templates/supernova.glb

Closes #141: reading the binning from channels file and use it in template

---

.github/workflows/integration.yml

Add integration test for SimpleRate

Update integration.yml to include SimpleRate

---

doc/nb/AnalyticFluence.ipynb
doc/nb/SNOwGLoBES_usage.ipynb
doc/source/conf.py
doc/source/models.rst
doc/source/snowglobes.rst
python/snewpy/from_snowglobes.py
python/snewpy/models/base.py
python/snewpy/models/ccsn.py
python/snewpy/run_snowglobes.py
python/snewpy/scripts/SNEWS2.0_rate_table.py
python/snewpy/scripts/SNEWS2.0_rate_table_singleexample.py
python/snewpy/scripts/TimeSeries.py
python/snewpy/scripts/snewpy_to_snewpdag.py
python/snewpy/snowglobes.py
python/snewpy/snowglobes_interface.py
python/snewpy/test/simplerate_integrationtest.py
python/snewpy/test/snowglobes_integrationtest.py
python/snewpy/test/test_snowglobes.py

In preparation for releasing v1.2, this PR contains documentation fixes and removes deprecated parameters from sample notebooks/scripts.
Ideally, these sorts of things should be included in the same PR that introduces the changes; it looks like both PR authors and reviewers (myself included) missed that. Wonder if it’s worth adding [a PR template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) with checkmarks for docs, tests, sample code, etc.?

Cleanup to prepare v1.2

---

python/snewpy/snowglobes_interface.py

Work on `SimpleRate`
Closes #216 
Closes #218

Moving reading flux files to SimpleRate.run function, remove hardcoded binning

---

python/snewpy/models/base.py

Adding get_flux function to SupernovaModel

---

python/snewpy/_model_downloader.py
python/snewpy/models/ccsn.py

Fixes failing integration test, the result of a call between @JostMigenda and myself. The error was related to handling of absolute paths to model files.

Fix integration test

---

python/snewpy/models/base.py

Using time arrays in PinchedModel.get_initial_spectra

---

.github/workflows/integration.yml
.github/workflows/publish.yml
.github/workflows/tests.yml
doc/source/contributing.rst
python/snewpy/_git.py
python/snewpy/_model_downloader.py
python/snewpy/models/__init__.py
python/snewpy/models/base.py
python/snewpy/scripts/Analytic.py
python/snewpy/snowglobes.py
python/snewpy/snowglobes_interface.py
python/snewpy/test/test_05_snowglobes.py

Various bits of cleanup that are too small to deserve separate PRs. See commit messages for details.

minor fixes

---

python/snewpy/models/base.py
python/snewpy/models/loaders.py

Possible solution for [issue #298](https://github.com/SNEWS2/snewpy/issues/298)

Fix bug in treatment of the E=0 point for fluences

---

doc/nb/AnalyticFluence.ipynb

Improved default path in AnalyticFluence.ipynb

---

.github/workflows/integration.yml
.github/workflows/publish.yml
.github/workflows/tests.yml
python/snewpy/__init__.py
python/snewpy/flux.py
python/snewpy/models/presn_loaders.py
python/snewpy/rate_calculator.py
python/snewpy/snowglobes_interface.py

* Fixes #305
* removes unused imports and a superfluous return statement
* updates GitHub actions to latest version
* replaces depracated argument to some pandas API calls

Various bits of cleanup

---

python/snewpy/models/presn_loaders.py

Fixes #321, see explanation there.

Fix normalisation of nu_x fluxes for Odrzywolek_2010

---

.github/workflows/integration.yml
.github/workflows/tests.yml

A proposed workflow to work on specific (larger) releases:
* create a branch `release_v*`
* all changes go to that branch 
* rules similar to the `main`: all PRs need a review and pass the tests

Run tests for the  branches with the name `"release_*"`

---

python/snewpy/scripts/SNEWS2.0_rate_table.py
python/snewpy/snowglobes_interface.py

To the rate table code, added KM3NeT, integrated DarkSide-20k, XENONnT, LZ, and PandaX-4T to be calculated like the rest of the detectors, and fill in spots that were previously "-". As well as formatting it to output formatted to create an html table utilizing mathjax. Also had to add LZ & PandaX-4T into the snowglobes_interface.py for those integrations to work. I added the html rate table code as its own file rather than replacing the existing one, but that could be changed if desired!

Rate table & snowglobes interface update

---

python/snewpy/__init__.py

Release version 1.6

---

doc/source/contributing.rst
doc/source/snowglobes.rst
python/snewpy/rate_calculator.py
python/snewpy/snowglobes_interface.py

Closes #371; see reasoning there.

Remove support for `$SNOWGLOBES` environment variable
